const content = JSON.parse(localStorage.getItem('portfolioContent') || 'null') || window.PORTFOLIO_CONTENT;
const $ = (id) => document.getElementById(id);
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pills = (items=[]) => items.map(t => `<span class="pill">${esc(t)}</span>`).join('');
function setTheme(){const saved=localStorage.getItem('theme');const dark=saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light'}
function toggleTheme(){const next=document.documentElement.dataset.theme!=='dark';localStorage.setItem('theme',next?'dark':'light');setTheme()}
function nav(){document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.addEventListener('click',toggleTheme))}
function renderHome(){if(!$('home-root'))return;const p=content.profile;document.title=`${p.name} | Research Portfolio`;$('hero').innerHTML=`<div class="reveal"><p class="eyebrow">Researcher · Scientist · Engineer</p><h1>${esc(p.name)}</h1><p class="tag">${esc(p.tagline)}</p><p>${esc(p.intro)}</p><div class="actions"><a class="btn primary" href="#research">View Research</a><a class="btn" href="#projects">View Projects</a><a class="btn" href="${esc(p.cv)}">Download CV</a><a class="btn" href="#contact">Contact Me</a></div><div class="social"><a href="mailto:${esc(p.email)}">Email</a>${Object.entries(p.links).map(([k,v])=>v?`<a href="${esc(v)}">${esc(k)}</a>`:`<span class="muted">${esc(k)} placeholder</span>`).join('')}</div></div><div class="card viz" aria-label="Subtle scientific visualization"><span class="node n1"></span><span class="node n2"></span><span class="node n3"></span></div>`;
$('research-grid').innerHTML=content.researchInterests.map(r=>`<article class="card"><h3>${esc(r.title)}</h3><p class="muted">${esc(r.text)}</p></article>`).join('');
$('projects-grid').innerHTML=content.projects.map(pr=>`<a class="card project-link" href="projects/${pr.slug}.html"><img class="thumb" loading="lazy" src="${esc(pr.thumbnail)}" alt="${esc(pr.title)} thumbnail"><p class="eyebrow">${esc(pr.category)} · ${esc(pr.status)}</p><h3>${esc(pr.title)}</h3><p class="muted">${esc(pr.shortDescription)}</p>${pills(pr.technologies)}</a>`).join('');
$('pubs').innerHTML=content.publications.map(pub=>`<article class="paper"><p class="eyebrow">${esc(pub.status)}</p><h3>${esc(pub.title)}</h3><p>${esc(pub.authors)}</p><p class="muted">${esc(pub.venue)}</p></article>`).join('');
$('about-card').innerHTML=`<p>${esc(p.about)}</p>`;$('skills-card').innerHTML='<h3>Technical Skills</h3>'+content.skills.map(s=>`<p><strong>${esc(s.group)}:</strong> ${esc(s.items.join(', '))}</p>`).join('');
$('experience-list').innerHTML=content.experience.map(e=>`<article class="timeline"><p class="eyebrow">${esc(e.date)} · ${esc(e.location)}</p><h3>${esc(e.position)}</h3><p><strong>${esc(e.organization)}</strong></p><ul>${e.highlights.map(h=>`<li>${esc(h)}</li>`).join('')}</ul></article>`).join('');
$('education-list').innerHTML=content.education.map(e=>`<article class="timeline"><p class="eyebrow">${esc(e.date)} · ${esc(e.location)}</p><h3>${esc(e.degree)}</h3><p><strong>${esc(e.institution)}</strong></p><p>${esc(e.grade)}</p>${e.details.map(d=>`<p class="muted">${esc(d)}</p>`).join('')}</article>`).join('');
$('cv-card').innerHTML=`<p class="muted">Replace the placeholder PDF by uploading your final CV file to assets/cv and updating content.js or imported admin JSON.</p><a class="btn primary" href="${esc(p.cv)}">Download CV (PDF)</a>`;
$('contact-card').innerHTML=`<p>Email: <a href="mailto:${esc(p.email)}">${esc(p.email)}</a></p><p class="muted">Phone is kept in structured content but not emphasized publicly.</p><p>References available upon request.</p>`;
$('awards-grid').innerHTML=content.awards.map(a=>`<div class="card">${esc(a)}</div>`).join('');
}
function renderProject(){const root=$('project-root');if(!root)return;const slug=root.dataset.slug;const pr=content.projects.find(x=>x.slug===slug);if(!pr){root.innerHTML='<div class="container"><h1>Project not found</h1></div>';return}document.title=`${pr.title} | Shivam Kumar Jha`;root.innerHTML=`<div class="container" style="padding-top:4rem"><p class="eyebrow">${esc(pr.category)} · ${esc(pr.date)} · ${esc(pr.status)}</p><h1 class="page-title">${esc(pr.title)}</h1><p class="tag">${esc(pr.shortDescription)}</p><img class="thumb" loading="lazy" src="../${esc(pr.thumbnail)}" alt="${esc(pr.title)}"><div class="two" style="margin-top:1rem"><section class="card"><h2>Overview</h2><p>${esc(pr.overview)}</p></section><section class="card"><h2>Motivation</h2><p>${esc(pr.motivation)}</p></section><section class="card"><h2>Methodology</h2><p>${esc(pr.methodology)}</p></section><section class="card"><h2>Results</h2><ul>${pr.keyResults.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></section><section class="card"><h2>My Contribution</h2><p>${esc(pr.contribution)}</p></section><section class="card"><h2>Resources</h2><div class="actions">${Object.entries(pr.links).filter(([,v])=>v).map(([k,v])=>`<a class="btn" href="${esc(v)}">${esc(k)}</a>`).join('') || '<span class="muted">Links pending.</span>'}</div></section></div></div>`}
function renderAdmin(){if(!$('admin-root'))return;const rows=[['Projects',content.projects.length],['Publications',content.publications.length],['Research Interests',content.researchInterests.length],['Education',content.education.length],['Experience',content.experience.length],['Skills',content.skills.length],['Awards',content.awards.length],['Media','Upload'],['CV','Replace'],['Homepage','Edit']];$('admin-grid').innerHTML=rows.map(r=>`<article class="admin-card"><p class="eyebrow">${esc(r[1])} item(s)</p><h3>${esc(r[0])}</h3><p class="muted">Static GitHub Pages editor: export/import JSON, then commit updated content.js for public persistence.</p><button class="primary" type="button">Manage</button><button type="button">Preview</button></article>`).join('');$('json-editor').value=JSON.stringify(content,null,2);$('save-json').onclick=()=>{localStorage.setItem('portfolioContent',$('json-editor').value);alert('Saved draft to this browser. Use Export JSON and commit changes to content.js for GitHub Pages publication.')};$('reset-json').onclick=()=>{localStorage.removeItem('portfolioContent');location.reload()};$('export-json').onclick=()=>{const blob=new Blob([$('json-editor').value],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-content.json';a.click()}}
setTheme();addEventListener('DOMContentLoaded',()=>{nav();renderHome();renderProject();renderAdmin()});
